local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: "AKIATWEDMWND4NXIAQDP"
  secret_access_key: "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"
  region: ""
  bucket: "comment-processor"